#!/bin/bash

files=( data/*.sqfs )

newest=${files[-1]}

date2=${newest%.sqfs}
date2=${date2#data/portage-}
newestfn=${newest##*/}

for (( i = ${#files[@]} - 2; i >= 0; i-- )); do
	f=${files[${i}]}
	date1=${f%.sqfs}
	date1=${date1#data/portage-}
	oldfn=${f##*/}

	out=snapshot-${date1}-${date2}.sqfs.vcdiff

	echo "all: ${out}"
	echo "${out}: ${oldfn} ${newestfn}"
	echo "	xdelta3 -9 -S djw -e -s $< ${newestfn} \$@"
	echo "	[ \$\$(stat -c %s \$@) -lt \$\$(stat -c %s ${newestfn}) ]"
done >data/Makefile

make ${MAKEOPTS:--j4} -C data
rm data/Makefile
